from django.urls import path
from tutor import views

urlpatterns = [
    path('', views.Index, name='index'),
    path('login', views.Login1, name='login'),
    path('invaliduser', views.InvalidUser),
    path('home-admin', views.Home_Admin, name='home-admin'),
    path('studenttable-admin', views.StudentTable_Admin, name='studenttable-admin'),
    path('tutortable-admin', views.TutorTable_Admin, name='tutortable-admin'),
    path('approveorreject', views.ApproveOrReject, name='approveorreject'),
    path('approve/<id>', views.Approve, name='approve'),
    path('reject/<id>', views.Reject, name='reject'),
    path('courseadd', views.CourseAdd, name='courseadd'),
    path('coursetable-admin', views.CourseTable_Admin, name='coursetable-admin'),
    path('delete/<id>', views.Delete, name='delete'),
    path('subjectadd', views.SubjectAdd, name='subjectadd'),
    path('subjecttable-admin', views.SubjectTable_Admin, name='subjecttable-admin'),
    path('delete2/<id>', views.Delete2, name='delete2'),
    path('subjectallocation', views.SubjectAllocation, name='subjectallocation'),
    path('allocationtable', views.AllocationTable, name='allocationtable'),
    path('delete3/<id>', views.Delete3, name='delete3'),
    path('complainttable-admin', views.ComplaintTable_Admin, name='complainttable-admin'),
    path('reply/<id>', views.Reply, name='reply'),
    path('feedbacktable', views.FeedbackTable, name='feedbacktable'),
    path('changepassword-admin', views.ChangePassword_Admin, name='changepassword-admin'),
    path('chngpsadmn', views.ChangePasswordAdmn),
    path('tutorregistration', views.TutorRegistration, name='tutorregistration'),
    path('home-tutor', views.Home_Tutor, name='home-tutor'),
    path('tutorprofile', views.Tutor_Profile, name='tutorprofile'),
    path('coursetable-tutor', views.CourseTable_Tutor, name='coursetable-tutor'),
    path('subjecttable-tutor/<id>', views.SubjectTable_Tutor, name='subjecttable-tutor'),
    path('subjectselect/<id>', views.SubjectSelect, name='subjectselect'),
    path('selectedsubject-table', views.View_SelectedSubject, name='selectedsubject-table'),
    path('classupload/<id>', views.ClassUpload, name='classupload'),
    path('classtable-tutor', views.ClassTable_Tutor, name='classtable-tutor'),
    path('delete5/<id>', views.Delete5, name='delete5'),
    path('materials/<id>', views.Material, name='materials'),
    path('materialstable-tutor', views.MaterialsTable_Tutor, name='materialstable-tutor'),
    path('delete4/<id>', views.Delete4, name='delete4'),
    path('studenttable-tutor', views.StudentTable_Tutor, name='studenttable-tutor'),
    path('tutorchat/<id>', views.TutorChat, name='tutorchat'),
    path('changepassword-tutor', views.ChangePassword_Tutor, name='changepassword-tutor'),
    path('chngpsttr', views.ChangePasswordTtr),
    path('studentregistration', views.StudentRegistration, name='studentregistration'),
    path('home-student', views.Home_Student, name='home-student'),
    path('studentprofile', views.Student_Profile, name='studentprofile'),
    path('coursetable-student', views.CourseTable_Student, name='coursetable-student'),
    path('subjecttable-student/<id>', views.SubjectTable_Student, name='subjecttable-student'),
    path('classtable-student/<id>', views.ClassTable_Student, name='classtable-student'),
    path('materialstable-student/<id>', views.MaterialsTable_Student, name='materialstable-student'),
    path('tutortable-student/<id>', views.TutorTable_Student, name='tutortable-student'),
    path('studentchat/<id>', views.StudentChat, name='studentchat'),
    path('complaint', views.student_Complaint, name='complaint'),
    path('complainttable-student', views.ComplaintTable_Student, name='complainttable-student'),
    path('feedbackform', views.FeedbackForm, name='feedbackform'),
    path('changepassword-student', views.ChangePassword_Student, name='changepassword-student'),
    path('chngpsstd', views.ChangePasswordStd, name='chngpsstd'),
    path('logout', views.Logout, name='logout'),
    path('log', views.Log, name='log'),
    path('reg', views.Reg, name='reg'),
    path('prof', views.Profile_Android, name='prof'),
    path('viewcourse', views.ViewCourse_Android, name='viewcourse'),
    path('viewclass', views.ViewClass_Android, name='viewclass'),
    path('viewnotes', views.ViewNotes_Android, name='viewnotes'),
    path('viewsubject', views.ViewSubject_Android, name='viewsubject'),
    path('viewtutor', views.ViewTutor_Android, name='viewtutor'),
    path('sendchat', views.SendChat_Android, name='sendchat'),
    path('chat', views.ViewChat_Android, name='chat'),
    path('comp', views.Complaint_Android, name='comp'),
    path('viewreply', views.ViewReply_Android, name='viewreply'),
    path('feed', views.Feedback_Android, name='feed'),
    path('changeps', views.ChangePassword_Android, name='changeps'),
]